apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ui-ingress
  namespace: agrotech
  annotations:
    # Se você estiver usando Nginx Ingress Controller (padrão)
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # "true" se já tiver cert-manager configurado
    # Se o upload de mensagens JSON grandes falhar, aumente isso:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
  - host: kafka.interglobaltecnologia.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kafka-ui-svc # Nome do Service criado no passo anterior
            port:
              number: 80       # Porta externa do Service