apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgis-pvc
  namespace: agrotech
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-vm-storage # <--- AQUI: ForÃ§ando o NFS
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis
  namespace: agrotech
spec:
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
    spec:
      containers:
      - name: postgis
        image: postgis/postgis:15-3.3
        env:
        - name: POSTGRES_USER
          value: "agro_admin"
        - name: POSTGRES_PASSWORD
          value: "%%%%%3Filhos32023@@"
        - name: POSTGRES_DB
          value: "agrotech_db"
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgis-storage
      volumes:
      - name: postgis-storage
        persistentVolumeClaim:
          claimName: postgis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgis-svc
  namespace: agrotech
spec:
  type: NodePort
  selector:
    app: postgis
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30432