apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mosquitto-ingress
  namespace: agrotech
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "mosquitto-svc"
    # Se usar Cert-Manager:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - mosquitto.interglobaltecnologia.com.br
    secretName: mosquitto-tls
  rules:
  - host: mosquitto.interglobaltecnologia.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mosquitto-svc
            port:
              number: 9001