apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: agro-cluster
  namespace: agrotech
  annotations:
    strimzi.io/node-pools: "enabled" # Ativa o novo formato de pools
    strimzi.io/kraft: "enabled"      # Ativa o modo sem Zookeeper
spec:
  kafka:
    version: 4.0.0 # Versão compatível com seu Operator 0.49.1
    metadataVersion: 4.0-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport # Acesso externo para testes
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      # Configurações específicas do KRaft
      process.roles: broker,controller
      node.id: 0
      controller.quorum.voters: 0@agro-cluster-pool-0:9093