apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: agro-cluster
  namespace: agrotech
  annotations:
    strimzi.io/node-pools: "enabled"
    strimzi.io/kraft: "enabled"
spec:
  kafka:
    version: 3.7.0
    metadataVersion: 4.1-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 30094 # <--- PORTA FIXA para o HAProxy
          brokers:
          - broker: 0
            # O Kafka precisa anunciar o endereço que o Endian expõe para a internet
            advertisedHost: kafka.interglobaltecnologia.com.br 
            advertisedPort: 9094 # A porta que o Endian expõe pra fora
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1