apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: agro-connect
  namespace: agrotech
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  replicas: 1
  bootstrapServers: agro-cluster-kafka-bootstrap:9092
  
  # AQUI: Aponte para a imagem que vocÃª acabou de criar no Passo 2
  # Exemplo: gutemberg/agro-connect-mqtt:1.0 (substitua pelo seu)
  image: eurival/agro-connect-mqtt:1.0
  
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    # Importante: O caminho onde colocamos o JAR no Dockerfile
    plugin.path: /opt/kafka/plugins