apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: agro-connect
  namespace: agrotech
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  replicas: 1
  
  # Endereço do Kafka
  bootstrapServers: agro-cluster-kafka-bootstrap:9092
  
  # Sua imagem 3.0 (que está boa)
  image: eurival/agro-connect-mqtt:3.0

  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1000m

  # --- CONFIGURAÇÃO DE TEMPLATE (CORRIGIDA) ---
  # No Strimzi, para mexer no container do Connect, usamos 'connectContainer'
  template:
    connectContainer:
      env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "agro-cluster-kafka-bootstrap:9092"
        - name: KAFKA_CONNECT_PLUGIN_PATH
          value: "/opt/kafka/plugins"

  # Sem seção 'logging' (usa o padrão da imagem para não dar erro de arquivo)

  config:
    # Redundância de segurança
    bootstrap.servers: agro-cluster-kafka-bootstrap:9092
    
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    offset.flush.interval.ms: 10000
    
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    
    plugin.path: /opt/kafka/plugins