apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: agro-connect
  namespace: agrotech
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  replicas: 1
  
  # Endereço do Kafka (Isso preenche o bootstrap.servers automaticamente)
  bootstrapServers: agro-cluster-kafka-bootstrap:9092
  
  # IMAGEM NOVA 3.0 (Com permissões corrigidas)
  image: eurival/agro-connect-mqtt:3.0

  # Log Inline (O operador gera isso automaticamente)
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "INFO"
      
  # Recursos
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1000m

  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    offset.flush.interval.ms: 10000
    
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    
    plugin.path: /opt/kafka/plugins