apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: agro-connect
  namespace: agrotech
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  replicas: 1
  bootstrapServers: agro-cluster-kafka-bootstrap:9092
  
  image: eurival/agro-connect-mqtt:3.0

  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1000m

  # --- SOLUÇÃO DO LOG: Corrigindo o NOME do arquivo ---
  # Isso faz o Strimzi gerar um ConfigMap com o NOME correto
  logging:
    type: inline
    # O Strimzi usa o campo `loggers` para gerar o arquivo, 
    # mas alguns pods antigos procuram o nome 'log4j.properties'. 
    # Vamos usar o formato que força o nome correto:
    loggers:
      connect.root.logger.level: "INFO"
      
  # Injeção manual do Bootstrap (para garantir)
  template:
    connectContainer:
      env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "agro-cluster-kafka-bootstrap:9092"

  config:
    # Redundância de segurança
    bootstrap.servers: agro-cluster-kafka-bootstrap:9092
    
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    offset.flush.interval.ms: 10000
    
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    
    plugin.path: /opt/kafka/plugins