apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: agro-connect
  namespace: agrotech
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  replicas: 1
  
  # Endereço do Kafka (Obrigatório na spec)
  bootstrapServers: agro-cluster-kafka-bootstrap:9092
  
  # Sua imagem customizada
  image: eurival/agro-connect-mqtt:1.0

  # --- CORREÇÃO 1: Recursos ficam na raiz da spec ---
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1000m

  # Configuração de Log Inline (Para evitar erro de arquivo não encontrado)
  logging:
    type: inline
    loggers:
      connect.root.logger.level: INFO
  
  # --- CORREÇÃO 2: Forçamos o endereço aqui dentro do config ---
  config:
    # Isso garante que a propriedade exista mesmo se a automação falhar
    bootstrap.servers: agro-cluster-kafka-bootstrap:9092
    
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    offset.flush.interval.ms: 10000
    
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    
    plugin.path: /opt/kafka/plugins

  # Template limpo (removidos os campos inválidos)
  template:
    pod:
      metadata:
        annotations:
          # Apenas uma annotation de exemplo para garantir que o bloco existe
          strimzi.io/generation: "1"