apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: agro-connect
  namespace: agrotech
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  replicas: 1
  bootstrapServers: agro-cluster-kafka-bootstrap:9092
  
  # Sua imagem 5.0 (com a correção embutida do log4j.properties)
  image: eurival/agro-connect-mqtt:5.0

  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1000m
  
  # --- O BYPASS DO VOLUME DE CONFIGURAÇÃO (Sintaxe Strimzi) ---
  template:
    # 1. Removendo a montagem do volume 'kafka-config' para o custom-config
    connectContainer:
      volumeMounts:
        # Sobrescrevemos a montagem do volume padrão do Strimzi
        # Excluindo a montagem para /opt/kafka/custom-config
        - name: kafka-config
          mountPath: /opt/kafka/config
        - name: kafka-config
          mountPath: /opt/kafka/init
          
    # 2. Definimos os volumes que o Strimzi precisa
    pod:
      volumes:
        - name: kafka-config
          configMap:
            name: agro-connect-connect-config # Nome do ConfigMap gerado pelo Strimzi

  config:
    bootstrap.servers: agro-cluster-kafka-bootstrap:9092
    
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    offset.flush.interval.ms: 10000
    
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    
    plugin.path: /opt/kafka/plugins