apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: agro-connect
  namespace: agrotech
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  replicas: 1
  
  # Endereço do Kafka
  bootstrapServers: agro-cluster-kafka-bootstrap:9092
  
  # NOVA IMAGEM 2.0
  image: eurival/agro-connect-mqtt:2.0

  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1000m

  # Removemos a seção 'logging' propositalmente.
  # Isso força o Strimzi a usar o log4j padrão embutido na imagem,
  # eliminando o erro de FileNotFound.
  
  config:
    # Segurança extra: Forçar o endereço aqui
    bootstrap.servers: agro-cluster-kafka-bootstrap:9092
    
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    offset.flush.interval.ms: 10000
    
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    
    plugin.path: /opt/kafka/plugins