apiVersion: kafka.strimzi.io/v1  # <--- MUDANÇA CRUCIAL: Agora usamos v1
kind: KafkaConnect
metadata:
  name: agro-connect
  namespace: agrotech
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 4.1.1 # Mantendo a mesma versão que você definiu no Kafka
  replicas: 1
  bootstrapServers: agro-cluster-kafka-bootstrap:9092
  
  image: eurival/agro-connect-mqtt:9.1

  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1000m
  
  config:
    # Configurações do Worker
    bootstrap.servers: agro-cluster-kafka-bootstrap:9092
    group.id: connect-cluster
    offset.flush.interval.ms: 10000
    
    # Fator 1 para cluster single-node
    config.storage.replication.factor: 1
    status.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    offset.storage.topic: connect-cluster-offsets
    
    # Conversores (JSON simples para facilitar debug)
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false