apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: agro-connect
  namespace: agrotech
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  replicas: 1
  
  # Endereço "Oficial" (usado pelo Operador)
  bootstrapServers: agro-cluster-kafka-bootstrap:9092
  
  # Sua imagem customizada
  image: eurival/agro-connect-mqtt:1.0
  
  # Recursos (mantive pois estava correto)
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1000m

  # Bloco de Configuração Interna
  config:
    # --- O PULO DO GATO ---
    # Estamos forçando o endereço aqui dentro também.
    # Isso preenche a linha vazia que estava matando o processo.
    bootstrap.servers: agro-cluster-kafka-bootstrap:9092
    
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    offset.flush.interval.ms: 10000
    
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    
    plugin.path: /opt/kafka/plugins