apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: agro-connect
  namespace: agrotech
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  replicas: 1
  
  # Endereço interno do cluster Kafka (Confira se o nome bate com o passo 01)
  bootstrapServers: agro-cluster-kafka-bootstrap:9092
  
  # A imagem customizada que você criou com o plugin
  # IMPORTANTE: Garanta que essa imagem existe no seu Docker Hub
  image: seu-usuario/agro-connect-mqtt:1.0 
  
  # Configuração de Log INLINE (Isso resolve o erro do log4j)
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "INFO"
      
  # Recursos para evitar travamentos
  template:
    pod:
      resources:
        requests:
          memory: 512Mi
          cpu: 500m
        limits:
          memory: 1Gi
          cpu: 1000m

  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # Aumentei o timeout para evitar desconexões
    offset.flush.interval.ms: 10000
    
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    
    # Caminho onde colocamos o jar no Dockerfile
    plugin.path: /opt/kafka/plugins