apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: agro-connect
  namespace: agrotech
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  replicas: 1
  bootstrapServers: agro-cluster-kafka-bootstrap:9092
  
  # Sua imagem correta
  image: eurival/agro-connect-mqtt:1.0
  
  # --- CORREÇÃO 1: Resources vem direto aqui, não no template ---
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1000m

  # --- CORREÇÃO 2: Configuração de Log Inline ---
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "INFO"
  
  # Configurações do Kafka Connect
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    offset.flush.interval.ms: 10000
    
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    
    plugin.path: /opt/kafka/plugins

  # Template deixamos vazio ou removemos se não for usar labels extras
  # (Se não precisar customizar labels do pod, pode até apagar esse bloco template)
  template:
    pod:
      metadata:
        annotations:
          cloud.google.com/neg: '{"ingress": true}' # Exemplo, pode remover se não usar