apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: agro-connect
  namespace: agrotech
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 4.1.1 # Alinhado com o cluster
  replicas: 1
  
  bootstrapServers: agro-cluster-kafka-bootstrap:9092
  
  # IMAGEM 9.1 (A mais recente que você subiu)
  image: eurival/agro-connect-mqtt:9.1

  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1000m
  
  config:
    bootstrap.servers: agro-cluster-kafka-bootstrap:9092
    
    group.id: connect-cluster
    offset.flush.interval.ms: 10000
    
    # --- CORREÇÃO DO FATOR DE REPLICAÇÃO ---
    # Seu cluster só tem 1 broker, então a replicação máxima é 1.
    config.storage.replication.factor: 1
    status.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    offset.storage.topic: connect-cluster-offsets
    
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    
    plugin.path: /opt/kafka/plugins