apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: agro-connect
  namespace: agrotech
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  replicas: 1
  bootstrapServers: agro-cluster-kafka-bootstrap:9092
  
  # Sua imagem 3.0 (que tem as permissões 1001 corretas)
  image: eurival/agro-connect-mqtt:3.0

  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1000m

  # --- CORREÇÃO DO LOGGING (LOG4J 2) ---
  # Usamos 'inline' para o Operator criar o arquivo sozinho.
  # A sintaxe abaixo é compatível com Kafka 3.x
  logging:
    type: inline
    loggers:
      log4j.rootLogger: "INFO"
      loggers.zookeeper.name: "org.apache.zookeeper"
      loggers.zookeeper.level: "WARN"
  
  config:
    # Bootstrap Servers
    bootstrap.servers: agro-cluster-kafka-bootstrap:9092
    
    # Configurações Padrão
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    offset.flush.interval.ms: 10000
    
    # Conversores
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    
    # Plugin Path
    plugin.path: /opt/kafka/plugins