apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: agro-connect
  namespace: agrotech
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  replicas: 1
  bootstrapServers: agro-cluster-kafka-bootstrap:9092
  
  # Imagem 3.0 (Permissões 1001 OK)
  image: eurival/agro-connect-mqtt:3.0

  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1000m

  # AQUI: Apontamos para o ConfigMap do Passo 2
  # Isso evita o FileNotFoundException
  logging:
    type: external
    valueFrom:
      configMapKeyRef:
        name: connect-logging
        key: log4j.properties

  config:
    # Bootstrap forçado
    bootstrap.servers: agro-cluster-kafka-bootstrap:9092
    
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    offset.flush.interval.ms: 10000
    
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    
    plugin.path: /opt/kafka/plugins