apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: agro-connect
  namespace: agrotech
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  replicas: 1
  bootstrapServers: agro-cluster-kafka-bootstrap:9092
  
  # Imagem Oficial Limpa
  image: quay.io/strimzi/kafka:0.40.0-kafka-3.7.0
  
  # A Injeção do Plugin
  template:
    pod:
      volumes:
      - name: connector-plugins
        emptyDir: {}
      initContainers:
      - name: download-plugins
        image: busybox:1.36
        command: ["sh", "-c"]
        # Baixa, Deszipa e Move para a pasta correta
        args:
          - |
            echo "--- INICIANDO DOWNLOAD DO PLUGIN ---"
            mkdir -p /opt/kafka/plugins/mqtt
            wget -q -O /tmp/plugin.zip https://github.com/streamthoughts/kafka-connect-mqtt/releases/download/v2.3.0/streamthoughts-kafka-connect-mqtt-2.3.0.zip
            if [ $? -ne 0 ]; then echo "ERRO NO DOWNLOAD"; exit 1; fi
            unzip -q /tmp/plugin.zip -d /tmp/
            mv /tmp/streamthoughts-kafka-connect-mqtt-2.3.0/* /opt/kafka/plugins/mqtt/
            ls -R /opt/kafka/plugins/mqtt
            echo "--- SUCESSO ---"
        volumeMounts:
        - name: connector-plugins
          mountPath: /opt/kafka/plugins
      containers:
      - name: kafka-connect
        volumeMounts:
        - name: connector-plugins
          mountPath: /opt/kafka/plugins

  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    # Onde o Kafka vai ler os plugins baixados
    plugin.path: /opt/kafka/plugins