apiVersion: v1
kind: ConfigMap
metadata:
  name: connect-logging
  namespace: agrotech
data:
  log4j.properties: |
    # Joga tudo para o Console (stdout)
    log4j.rootLogger=INFO, stdout
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c)%n
    
    # Reduz o ru√≠do de logs chatos
    log4j.logger.org.reflections=WARN
    log4j.logger.org.apache.zookeeper=WARN
    log4j.logger.org.apache.kafka.clients=INFO