apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-vm-storage-retain-v3
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  onDelete: retain
  pathPattern: "${.PVC.namespace}-${.PVC.name}"
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - vers=3
  - proto=tcp
